### ISSUE TITLE
List of edited templates

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#72]
This issue is to keep track of all the templates made by the comms team. Please tick off once the individual issues have been closed. 

- [ ] Venue requirements template edits (https://github.com/softwaresaved/event-organisation-guide/issues/66)
- [ ] Risk Management template edits (https://github.com/softwaresaved/event-organisation-guide/issues/67) 
- [ ] Event timeline template edits (https://github.com/softwaresaved/event-organisation-guide/issues/68)
- [ ] Event Roles template edits (https://github.com/softwaresaved/event-organisation-guide/issues/69)
- [ ] Event Duties Roster template edits (https://github.com/softwaresaved/event-organisation-guide/issues/70)
- [ ] Budget template edits (https://github.com/softwaresaved/event-organisation-guide/issues/71)

**Comment by shoaibsufi** [comment]
All templates have been updated inline with the comms-edits2 work and are ready for final review - @selina-aragon and @JacalynLaird please make any update in place to these documents - there is no need to take a copy. Thanks.

https://drive.google.com/drive/folders/1DzSxtaGVkuFHGscBgR-1LyH1re3dm1x2

**Comment by shoaibsufi** [comment]
I will close the other related tickets above and this one once the final review is done - I have made any suggested changes from that and have uploaded the new versions to Zenodo.

**Comment by JacalynLaird** [comment]
> All templates have been updated inline with the comms-edits2 work and are ready for final review - @selina-aragon and @JacalynLaird please make any update in place to these documents - there is no need to take a copy. Thanks.
> 
> https://drive.google.com/drive/folders/1DzSxtaGVkuFHGscBgR-1LyH1re3dm1x2

There's an outstanding comment on the risk management spreadsheet that I can't change

**Comment by shoaibsufi** [comment]
It was referencing a different cell using a vlookup - I have updated the cell referenced so factots --> factors

**Comment by shoaibsufi** [comment]
All changes made (e.g. environment -> external factors in in the venue requirements) new files are now uploaded at these DOI permalinks:

Event Roles - https://doi.org/10.5281/zenodo.3967426
Event Duties Roster - https://doi.org/10.5281/zenodo.3967444
Venue Requirements - https://doi.org/10.5281/zenodo.4064078
Event Timeline - https://doi.org/10.5281/zenodo.4066930
Budget - https://doi.org/10.5281/zenodo.4071895
Risk Management - https://doi.org/10.5281/zenodo.4088023
